### ISSUE TITLE
Big Door Bug

### ISSUE THREAD

**Issue by ZiYueCommentary** [Jabka666/scpcb-ue-my#11]
When I open/close a big door, it didn't play any sounds.

But SFX folder has sound files, that's weird. 🤔 

I didn't find where bug happend, ~~why i cant add labels?~~

**Comment by Jabka666** [comment]
Check ``OpenCloseDoor`` function. Maybe something is wrong here

**Comment by ZiYueCommentary** [comment]
I found that BigDoor require sound at `OpenDoorSFX(3, 3)`, but seems max is (3, 2).

if we save big door sound with `(3, i + 1)`, it will play sounds!
