### ISSUE TITLE
WriteString error after trying to load or start a new game

### ISSUE THREAD

**Issue by Jabka666** [Jabka666/scpcb-ue-my#125]
![image.png](https://github.com/Jabka666/scpcb-ue-my/assets/41839972/7a53ae04-29db-476c-aa73-40d772f230fd)

**Comment by ZiYueCommentary** [comment]
Is this fixed?

**Comment by SnoeGit** [comment]
Caused by putting a space at the end

**Comment by SnoeGit** [comment]
Perhaps we can use 
CurrSave\Name = Replace(CurrSave\Name, " ", "_")

**Comment by ZiYueCommentary** [comment]
Just use trim and I think thats ok

**Comment by SnoeGit** [comment]
Should be resolved.
