### ISSUE TITLE
Suggestions for the new SCP and Rooms

### ISSUE THREAD

**Issue by Sanfrav** [Jabka666/scpcb-ue-my#129]
Is the Reborn Edition just for optimizing the original game?
 I think some rooms in the old version are quite interesting, such as room3ct in the NTF mod (although this is not good for game performance), but perhaps you can collect some rooms (SCP) on Discord. I thought you can improve the SCP-020.
Then you can add some necessary elements to the player, such as the need for a password to open a door of Gate B, and add some documents/prompts about the locked door of Gate B in certain rooms.
The above is only my personal opinion.

**Comment by ZiYueCommentary** [comment]
Closed as the opener requested.
