### ISSUE TITLE
Subtitles system

### ISSUE THREAD

**Issue by Jabka666** [Jabka666/scpcb-ue-my#13]
I still don't know how to finish my subtitles system :c

**Comment by ZiYueCommentary** [comment]
that's simple! i finished subtitle system but its chinese, maybe i need make them into english 😃 

oh and btw, in ending screen, FPSfactor will set to 0, and subtitle will stuck.
in vanilla we can use FPSFactor2 to instead and it can diaplay, but i dont know is fpsfactor2 exist in ue mod.

**Comment by Jabka666** [comment]
Oh, can I see how it works? It's very interesting!

**Comment by ZiYueCommentary** [comment]
Here it is! https://github.com/ZiYueCommentary/scpcb-chinese/blob/master/Data/subtitles.ini

Some subtitle was very long, maybe we need split them. 🧐

**Comment by EpicDasherFR** [comment]
Is there a "multi-subtitle" support in your system? A function that can play multiple subtitles at once. It is needed for WhatThe.ogg for example, because Ulgrin and Franklin talk at the same time, or during the German soldier speech, one in German, the other in the game language.

**Comment by ZiYueCommentary** [comment]
> Is there a "multi-subtitle" support in your system? A function that can play multiple subtitles at once. It is needed for WhatThe.ogg for example, because Ulgrin and Franklin talk at the same time, or during the German soldier speech, one in German, the other in the game language.

play multiple subtitles at once will get bugs

**Comment by EpicDasherFR** [comment]
I will take a look at your system and see if it would be possible to do

**Comment by EpicDasherFR** [comment]
Btw it doesn't have a link with the conversation, but if you have some textures PSD I'm interested, I'm currently making a French version of the game but I suck at Photoshop.

**Comment by ZiYueCommentary** [comment]
> Btw it doesn't have a link with the conversation, but if you have some textures PSD I'm interested, I'm currently making a French version of the game but I suck at Photoshop.

game will check does sound has subtitles when load sounds, subtitle will render when sound playing.

i store some PSD that i translated to chinese, maybe can help you.

https://github.com/ZiYueCommentary/scpcb-chinese/tree/master/psd%E5%AD%98%E6%A1%A3

**Comment by EpicDasherFR** [comment]
Your system work as the same as Jabka's once, making multi-subtitles implementation hard, if you have Discord I can maybe show you mine if you want. And thanks for these PSDs.

**Comment by Jabka666** [comment]
> > 
> 
> game will check does sound has subtitles when load sounds, subtitle will render when sound playing.

Yea, I chosen the same way, but tried to make them separately as "persons"

**Comment by ZiYueCommentary** [comment]
> Your system work as the same as Jabka's once, making multi-subtitles implementation hard, if you have Discord I can maybe show you mine if you want. And thanks for these PSDs.

my subtitle system basicly is Ctrl+C and Ctrl+V from ue mod.

and your subtitle system! that sounds cool, maybe you can upload to ue mod's discord.

https://discord.com/channels/571954180642701332/582832592139845633
