### ISSUE TITLE
Subtitles still showing when the player wearing SCP-1499

### ISSUE THREAD

**Issue by EasyT-T** [Jabka666/scpcb-ue-my#139]
### Subtitles still showing when the player wearing SCP-1499

**Version**
v1.2 (No translations)

**Description**
Subtitles still showing when the player wearing SCP-1499.

**Video**

https://github.com/Jabka666/scpcb-ue-my/assets/116633144/71a8be73-2587-4093-b334-cccd5315c00f

**Suggestion**
1. Make subtitles disappear in SCP-1499
2. Stop subtitles timer in SCP-1499
3. Restart subtitles timer when leaving SCP-1499

**Comment by ZiYueCommentary** [comment]
The subtitles will display to the end if it starts showing. This is a design characteristic and cannot be fixed.
