### ISSUE TITLE
Optimization system

### ISSUE THREAD

**Issue by Jabka666** [Jabka666/scpcb-ue-my#14]
Still can't finish optimization system hiding all objects located in the rooms that player doesn't see. ``Hide/ShowRooms`` functions in ``new_blend`` branch

**Comment by ZiYueCommentary** [comment]
blitz3d has high performance enough, maybe you dont need hide objects that player doesn't see.

~~why we dont re-add removed scps?~~

**Comment by Jabka666** [comment]
For some reason someone has low FPS. I don't know why

**Comment by Jabka666** [comment]
I'm still don't understand why. Maybe it's a problem of TSS Blitz or fixed time steps system

**Comment by ZiYueCommentary** [comment]
blitz3d tss is little diffierent with vanilla blitz3d, some project may have big performance problem.

but for scpcb, it shows better performance, i never met low fps in ue mod.

🤔

**Comment by Jabka666** [comment]
> blitz3d tss is little diffierent with vanilla blitz3d, some project may have big performance problem.
> 
> but for scpcb, it shows better performance, i never met low fps in ue mod.
> 
> 🤔

Are you talking about Reborn? Does it work better?

**Comment by ZiYueCommentary** [comment]
> > blitz3d tss is little diffierent with vanilla blitz3d, some project may have big performance problem.
> > but for scpcb, it shows better performance, i never met low fps in ue mod.
> > 🤔
> 
> Are you talking about Reborn? Does it work better?

in fact i only notice reborn runs a little bit smoother than original ue mod, i dont know does it work better.
