### ISSUE TITLE
Subtitles option out of the options panel

### ISSUE THREAD

**Issue by RedirectionFine** [Jabka666/scpcb-ue-my#141]
### Subtitles option out of the options panel

**Version**
v1.2 (No translations)

**Resolution**
1280*960 (Window)

**Description**
Subtitles option out of the options panel

**Image**
![image](https://github.com/Jabka666/scpcb-ue-my/assets/116633144/bc0a6610-56b0-475e-a0db-9b20e60fcaaa)

**Suggestion**
1. Add "Next" button to switch next page.

**Comment by SnoeGit** [comment]
Partially fixed with combined User Track settings. Still clips a bit unfortunately.
