### ISSUE TITLE
Russian loc download glitch

### ISSUE THREAD

**Issue by AlexNTFox** [Jabka666/scpcb-ue-my#145]
Доброго времени суток!

У меня не скачивается до конца архив с русской локализацией, а лишь часть. К примеру у меня не работает перевод загрузочных экранов, или некоторые модельки по прежнему используют оригинальные, английские сурсы, как например с моделькой класса D или когда охранник ругается на статую из пролога:

Можно ссылку на сам архив с переводом?

<img width="1280" alt="Desktop Screenshot 2024 04 24 - 02 31 41 22" src="https://github.com/Jabka666/scpcb-ue-my/assets/12477741/2ae5e9db-95da-49a5-9691-a2637feb84da">

**Comment by ZiYueCommentary** [comment]
Hi there, English please.

**Comment by Jabka666** [comment]
> Доброго времени суток!
> 
> У меня не скачивается до конца архив с русской локализацией, а лишь часть. К примеру у меня не работает перевод загрузочных экранов, или некоторые модельки по прежнему используют оригинальные, английские сурсы, как например с моделькой класса D или когда охранник ругается на статую из пролога:
> 
> Можно ссылку на сам архив с переводом?
> 
> <img alt="Desktop Screenshot 2024 04 24 - 02 31 41 22" width="1280" src="https://private-user-images.githubusercontent.com/12477741/325022605-2ae5e9db-95da-49a5-9691-a2637feb84da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5ODAzMDIsIm5iZiI6MTcxMzk4MDAwMiwicGF0aCI6Ii8xMjQ3Nzc0MS8zMjUwMjI2MDUtMmFlNWU5ZGItOTVkYS00OWE1LTk2OTEtYTI2MzdmZWI4NGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE3MzMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYzU2OTVmZDI3MzU4MjhhNGM3ZTY1Y2Q5ZjRlMzQ3Y2IwODg3ZDU0YWFhODhhNmJkZmNlZTE5MDM0OGI1YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DhmJmrV6PJPt342FD3KGqnM9rLOnuiWioVDInkxc8Cc">

Архив с русской локализацией полностью не готов. А то, что некоторые текстуры не переведены (хоть и есть в папке с игрой) - баг
