### ISSUE TITLE
No button sound sfx

### ISSUE THREAD

**Issue by EasyT-T** [Jabka666/scpcb-ue-my#149]
**Description**
No button sound when click menu or launcher button.

**Version**
1.2.2(1.3?) - UET_DEV

**Comment by ZiYueCommentary** [comment]
Yes they have

**Comment by EasyT-T** [comment]
Something wrong here.
First I started the game. No button sound.
But after I put this issue. It has button sound.
Weird.
I'm sure my ears are ok.

**Comment by EasyT-T** [comment]
I'm sure it still happened.

https://github.com/Jabka666/scpcb-ue-my/assets/116633144/c94ed9fc-06a5-4a34-84b8-740ab808bbe6

**Comment by Jabka666** [comment]
> I'm sure it still happened.
> 
>  2024-05-05_13-27-30.mp4

Does this still happen?

**Comment by EasyT-T** [comment]
> > I'm sure it still happened.
> > 2024-05-05_13-27-30.mp4
> 
> Does this still happen?

It doesn't seem like it's happening anymore.
Which even before was only a probability of happening.
Hopefully it won't happen again.
Close the issue so it shouldn't be a concern anymore.
