### ISSUE TITLE
LCZ room spawn in HCZ

### ISSUE THREAD

**Issue by EasyT-T** [Jabka666/scpcb-ue-my#160]
**[Version]** v1.2.1 - Released
**[Description]** room4_ic(ID 39) spawn in HCZ
**[Map Seed]** 2tw76c6q (Room Position 72.0 0.0 56.0)

**Comment by Jabka666** [comment]
- Probably fixed.

**Comment by EasyT-T** [comment]
Seems still happend.
Seed 2tw76c6q

![image](https://github.com/user-attachments/assets/ac4933f2-5f78-4f99-a96e-4371d911a8a5)

UET_DEV

**Comment by Jabka666** [comment]
Finally fixed
