### ISSUE TITLE
Some textures stop rendering after game missing focus in fullscreen

### ISSUE THREAD

**Issue by EasyT-T** [Jabka666/scpcb-ue-my#161]
Can you pause game when game is in background like non-reborn edition or original cb?
Because that can make player use FullScreen mode and freeze the game in background and the game ui will not be ruined.

Or you can make a switch button to switch this feature.

**Comment by ZiYueCommentary** [comment]
The game does pause when it is not focused.

**Comment by EasyT-T** [comment]
> The game does pause when it is not focused.

No, I mean you need freeze the game when the game is in background.
Seems like now the UI will not update/disappear when the game is minimize.
If you freeze the game, the UI will resume update when the game is in foreground.

If you do this, players can use dgVoodoo to use FullScreen mode and has a better experience.

**Comment by EasyT-T** [comment]
I may know why, does reborn has these code?
![image](https://github.com/Jabka666/scpcb-ue-my/assets/116633144/8c9e9ddc-5336-4154-9809-09446f39447d)

**Comment by Jabka666** [comment]
> > The game does pause when it is not focused.
> 
> No, I mean you need freeze the game when the game is in background. Seems like now the UI will not update/disappear when the game is minimize. If you freeze the game, the UI will resume update when the game is in foreground.
> 
> If you do this, players can use dgVoodoo to use FullScreen mode and has a better experience.

![image](https://github.com/Jabka666/scpcb-ue-my/assets/41839972/0e0f3a29-9b0b-4a36-a84e-b14d7c6edb26)

**Comment by EasyT-T** [comment]
> > > The game does pause when it is not focused.
> > 
> > 
> > No, I mean you need freeze the game when the game is in background. Seems like now the UI will not update/disappear when the game is minimize. If you freeze the game, the UI will resume update when the game is in foreground.
> > If you do this, players can use dgVoodoo to use FullScreen mode and has a better experience.
> 
> ![image](https://private-user-images.githubusercontent.com/41839972/335801909-0e0f3a29-9b0b-4a36-a84e-b14d7c6edb26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyODY0NDIsIm5iZiI6MTcxNzI4NjE0MiwicGF0aCI6Ii80MTgzOTk3Mi8zMzU4MDE5MDktMGUwZjNhMjktOWIwYi00YTM2LWE4NGUtYjE0ZDdjNmVkYjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDIzNTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYzAyZDQzN2I5YjEzMWJiOTFmOGVlMTQ5MTQ2MTgxOTNiY2JlNGUwOWJiMjgxYTY1ZjM2M2NmZmY1ZDUyZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AOtAm_g81DoL_PeeGBTYd2cD4cu2YCIMxesoZ2mXV2M)

Btw, so that is why the title changed to "Some textures stop rendering after game missing focus in fullscreen".
And it is not TSS Engine's problem, because ZiYue's sinicization version worked well.
There must something wrong is reborn.
And after textures stop rending, the "Active textures", "Video memory" or "Global memory status" haven't changed.

I contacted ZiYue, there are some videos may help you.

https://github.com/Jabka666/scpcb-ue-my/assets/116633144/65ce929b-7a62-4fc3-8793-eff6cbc620fa

This video shows I used fullscreen in non-reborn edition successfully. This can be not only in old UE, original game also can use Fullscreen with dgVoodoo.
After enter Alt+Tab (switch to desktop, same as minimize) and back to game, the menu's textures are working.


https://github.com/Jabka666/scpcb-ue-my/assets/116633144/667931b1-a8de-468a-a23f-34840c9b1fe9

This video shows I used fullscreen in reborn edition, after I enter Alt+Tab and back to game, the menu's textures were not rendering.

https://github.com/Jabka666/scpcb-ue-my/assets/116633144/ba54936d-a9f5-4e57-a577-8b8b06bb053c

This video shows I used fullscreen in reborn edition and in game, after I enter Alt+Tab and back to game, some ui's textures were not rendering.

**Comment by Jabka666** [comment]
I think it can be easily fixed by adding ``BufferDirty`` in ``LoadTextureCheckingInCache`` function, but it will require more RAM

**Comment by Jabka666** [comment]
- Fixed
