### ISSUE TITLE
[Normally it will not appear] A feature of Debug Mode don't work

### ISSUE THREAD

**Issue by EasyT-T** [Jabka666/scpcb-ue-my#162]
**[Version]** 1.2.1 with Debug Mode
**[Description]**
When you put the pointer on a square that means a room, the square should show the room name.
**[Image]** 
![image](https://github.com/Jabka666/scpcb-ue-my/assets/116633144/88bbd2dd-1816-46b4-862a-1e7d9a23747b)

**[Video]**

https://github.com/Jabka666/scpcb-ue-my/assets/116633144/fe11bb99-58e3-4d4d-9a87-e989d7b97db0

**Comment by Jabka666** [comment]
- Fixed
