### ISSUE TITLE
Move 'Localization' folder to Application Data

### ISSUE THREAD

**Issue by EasyT-T** [Jabka666/scpcb-ue-my#165]
I think you can move 'Localization' folder to Application Data ('scpcb-ue')

**Why?**
First, there's a bug that if you have many reborn version, then the language selector will think your language is the language you select before, but there's no any language in current folder, so the real language is the default language.
Second, move it to a constant folder can reduce storage space usage.

**Comment by ZiYueCommentary** [comment]
It is a design defect and not planned to be fixed.
