### ISSUE TITLE
Elevator Rotate Issue

### ISSUE THREAD

**Issue by EasyT-T** [Jabka666/scpcb-ue-my#166]
**[Version]** 1.2.1
**[Description]** 
The elevator of the maintenance tunnel turn the player around by 180 degrees which lead to an instant death if SCP-173 is outside when the doors open.

**Comment by Olexandr43** [comment]
I also had this annoying bug, but only with one elevator, don`t remember where(

**Comment by Jabka666** [comment]
*- Fixed (at least the chance of this issue is greatly reduced)
