### ISSUE TITLE
No cute skull wolf ladies :(

### ISSUE THREAD

**Issue by SillyLittleDoggo** [Jabka666/scpcb-ue-my#176]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/Jabka666/scpcb-ue-my/issues) before.
- [X] This bug still exists in the latest version of the Ultimate Edition Reborn.

### Describe the Bug

No cute clingy wolf ladies with attachment issues :(

### Reproduction Steps

1. Download Mal0
2. Continue to use Mal0
3. Profit

### Error Message Screenshot

idk what to put here so here's a banana 🍌

### Operating System Information

XBox gamers rise up

**Comment by ZiYueCommentary** [comment]
Don't you have more valuable things to do?

**Comment by SillyLittleDoggo** [comment]
> Don't you have more valuable things to do?

No :(
