### ISSUE TITLE
RuntimeErrorEx throws MemoryAccessViolation instead of telling what's the issue

### ISSUE THREAD

**Issue by Glebux** [Jabka666/scpcb-ue-my#179]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/Jabka666/scpcb-ue-my/issues) before.
- [X] This bug still exists in the latest version of the Ultimate Edition Reborn.

### Describe the Bug

When the game calls `RuntimeErrorEx%`, instead of telling the user what happened, it just throws a memory access violation, which is misleading.

### Reproduction Steps

1. Rename GFX/Menu/*any file*
2. Start the game

### Error Message Screenshot

![image](https://github.com/user-attachments/assets/0f0ad12f-1df5-4c02-a63a-0fd43c6a4453)

### Operating System Information

OS: ArchLinux Rolling
CPU: Intel i5 7400
WINE: wine-9.21.r0.gf03d32e3 ( TkG Staging Esync Fsync )
GPU: NVIDIA GTX 1060 3GB
VIDEO: dgVodoo2 81.3 -> DXVK GPLAsync 2.5.1
RAM: 16GB 2133MHz

### Extra Information

Expected behavior:
A message box telling the contents of `Message$`

**Comment by ZiYueCommentary** [comment]
`RuntimeErrorEx` will put the message into error messages with `CatchErrors`, and use `MemoryAccessViolation` to generate a MAV.

The situation that you reported happens in the early stage, in which error messages are not initiated yet.
