### ISSUE TITLE
Loading screens content bug

### ISSUE THREAD

**Issue by ZiYueCommentary** [Jabka666/scpcb-ue-my#25]
There are some non-latin characters appear in `loading_screens.ini`, but file's encoding is *Windows 1252*.

It means these characters will be invisible in game.

**Comment by Jabka666** [comment]
Can you show any example?

**Comment by ZiYueCommentary** [comment]
![image](https://user-images.githubusercontent.com/63241389/192099507-79872fa7-6fd8-4564-bc1e-860146d57e7b.png)

I did a simple test, my test shows they are invisible.

**Comment by Jabka666** [comment]
Is that all?

**Comment by ZiYueCommentary** [comment]
There is have more... but we can open file with Windows 1252, and save file with UTF-8 encoding to solve that.

**Comment by Jabka666** [comment]
I replaced some characters. Check the latest commit

**Comment by Jabka666** [comment]
Another question. Do you plan to make a multilanguage for UE? If yes, I will include it to v1.0.31

**Comment by ZiYueCommentary** [comment]
> Another question. Do you plan to make a multilanguage for UE? If yes, I will include it to v1.0.31

Yep, im really developing multi-language since i suggest this, but progress is sooooooo slow, the most complex part is language selector.

Multi-language maybe need change engine to [a branch of blitz3d tss](https://github.com/ZiYueCommentary/Blitz3D), this engine will make add less userlibs. If you dont like this, i will base on original blitz3d tss to develop multi-language.

**Comment by ZiYueCommentary** [comment]
> I replaced some characters. Check the latest commit

Line 16, 134, 269, 296 is still "half-commented", I'm not sure is that should keep be commented.

**Comment by Jabka666** [comment]
> > Another question. Do you plan to make a multilanguage for UE? If yes, I will include it to v1.0.31
> 
> Yep, im really developing multi-language since i suggest this, but progress is sooooooo slow, the most complex part is language selector.
> 
> Multi-language maybe need change engine to [a branch of blitz3d tss](https://github.com/ZiYueCommentary/Blitz3D), this engine will make add less userlibs. If you dont like this, i will base on original blitz3d tss to develop multi-language.

I will use your branch if it will be compatible with IDEal

**Comment by Jabka666** [comment]
> > I replaced some characters. Check the latest commit
> 
> Line 16, 134, 269, 296 is still "half-commented", I'm not sure is that should keep be commented.

![image](https://user-images.githubusercontent.com/41839972/192109390-cef41dd8-4fa8-4d7b-9221-022a9e6982d6.png)
As you can there aren't any problem with that. This isn't meant to be a comment

**Comment by ZiYueCommentary** [comment]
🤔 so the semicolon is a punctuation instead of comment

**Comment by Jabka666** [comment]
> 🤔 so the semicolon is a punctuation instead of comment

Yes, that's right, but as I said it doesn't affect on the text
