### ISSUE TITLE
Check dlls bug

### ISSUE THREAD

**Issue by ZiYueCommentary** [Jabka666/scpcb-ue-my#29]
When I searching for redundancy dlls, the game won't tell me dll is missing, it just crash.

**Comment by ZiYueCommentary** [comment]
Maybe thats cause by blitz tss, if a file is not exist, the engine will crash.

**Comment by Jabka666** [comment]
> By the way, should we delete https://github.com/Jabka666/scpcb-ue-my/tree/dev/Loadingscreens folder?

Why?

**Comment by ZiYueCommentary** [comment]
> > By the way, should we delete https://github.com/Jabka666/scpcb-ue-my/tree/dev/Loadingscreens folder?
> 
> Why?

I think it is useless, nothing is using them, and its easy to confusion with `LoadingScreens`.

**Comment by ZiYueCommentary** [comment]
New engine fixed this bug, maybe we can close this issue.
