### ISSUE TITLE
Language Selector bug

### ISSUE THREAD

**Issue by ZiYueCommentary** [Jabka666/scpcb-ue-my#41]
After changing the text's color from `1, 0, 0` to `0, 0, 0`, texts become disappear when the language amount to more than 13.

I don't know why so i set the color to `1, 0, 0` when developing, and i also notice the scroll bar won't work fine.

Stay too long in the selector also cause MAV, i don't know why because the debug mode didn't show anything.

And the `Map Creator` folder didn't contain the `Maps` folder, the game will crash when trying to get maps from the folder.

The achievement tooltip is down below the buttons.

**Comment by Jabka666** [comment]
For some reason image buffer doesn't work properly

**Comment by Jabka666** [comment]
Also I recommend to use ``Cls`` instead of drawing a new background image at negative coordinates

**Comment by Jabka666** [comment]
I think it's engine bug

**Comment by ZiYueCommentary** [comment]
> I think it's engine bug

Normally engine bug will crash immediately, and won't pop up mav dialog.

**Comment by Jabka666** [comment]
Shouldn't we also translate loading screens and SFX?

**Comment by ZiYueCommentary** [comment]
> Shouldn't we also translate loading screens and SFX?

Maybe I forgot them, we can make an "OpenFile_Strict" function to check the localized folder before opening the file in the game root path. Loadingscreens and credits should can translate.

About sfx, I think subtitles is better, if you want to translate sfx, I will make a pull request later.

**Comment by Jabka666** [comment]
> > Shouldn't we also translate loading screens and SFX?
> 
> Maybe I forgot them, we can make an "OpenFile_Strict" function to check the localized folder before opening the file in the game root path. Loadingscreens and credits should can translate.
> 
> About sfx, I think subtitles is better, if you want to translate sfx, I will make a pull request later.

Make a pull request for LoadingScreens (use no_opt branch)

**Comment by ZiYueCommentary** [comment]
By the way, when are you planning to release v1.0.4?

I'm developing "reborn of mav less" for my blitz3d tss, this may will easier to debug for bugs that players report, but this needs some time. 🤓

**Comment by Jabka666** [comment]
> By the way, when are you planning to release v1.0.4?
> 
> I'm developing "reborn of mav less" for my blitz3d tss, this may will easier to debug for bugs that players report, but this needs some time. 🤓

I'm planning to finish Russian translation (also textures and etc)

**Comment by ZiYueCommentary** [comment]
> > By the way, when are you planning to release v1.0.4?
> > I'm developing "reborn of mav less" for my blitz3d tss, this may will easier to debug for bugs that players report, but this needs some time. 🤓
> 
> I'm planning to finish Russian translation (also textures and etc)

Seems to need some time, maybe I can catch v1.0.4 😃

**Comment by Jabka666** [comment]
Oh, I found why translation didn't work! I didn't save a file as UTF-8

**Comment by Jabka666** [comment]
![image](https://user-images.githubusercontent.com/41839972/198841116-23cd1361-38a2-4da0-a037-6ac9ee3f050e.png)
For some reason background setting doesn't work

**Comment by ZiYueCommentary** [comment]
> ![image](https://user-images.githubusercontent.com/41839972/198841116-23cd1361-38a2-4da0-a037-6ac9ee3f050e.png) For some reason background setting doesn't work while using UTF-8 format

now game parses this value with integer, so only 0 or 1 takes effect. maybe you need write a function to parse "true" and "false" to `True` or `False`, use `IniGetBufferString_` function.
