### ISSUE TITLE
Gas Mask fogging not disappearing when saving and loading during fog

### ISSUE THREAD

**Issue by SnoeGit** [Jabka666/scpcb-ue-my#54]

**Comment by ZiYueCommentary** [comment]
I don't know what this issue is describing. 🤔 

if you mean "save game when wearing a gas mask, when load game, game will render gas mask fog": if you save game when wearing a gas mask, the save game will save that you are wearing gas mask.

**Comment by Jabka666** [comment]
That's weird. Fog timer is saved in save file https://github.com/Jabka666/scpcb-ue-my/blob/no_opt/Source%20Code/Save_Core.bb#L615

**Comment by Jabka666** [comment]
I think this was done on purpose, as Ultimate Edition tries to save absolutely everything, even the smallest parameters like blinking or stamina

**Comment by SnoeGit** [comment]
This is what I am talking about. The fogging doesn't go away at all once you reload. Pausing seems to fix it.

https://user-images.githubusercontent.com/97807054/204748881-70012df8-4e45-46db-8f5e-78733a723681.mp4

**Comment by ZiYueCommentary** [comment]
> This is what I am talking about. The fogging doesn't go away at all once you reload. Pausing seems to fix it.
> 
>  Foggingglitch.mp4

probably I understand, you may mean fogtimer will freeze when you're not wearing a gas mask?

**Comment by Jabka666** [comment]
Weird. Gonna check

**Comment by Jabka666** [comment]
Fixed
