### ISSUE TITLE
Blank game

### ISSUE THREAD

**Issue by ZiYueCommentary** [Jabka666/scpcb-ue-my#58]
This bug causes game to black when launching game from the launcher.

From my analysis, the problem happens on [`Graphics_Core.bb`](https://github.com/Jabka666/scpcb-ue-my/commit/3363d4364e7d561794dccd631294bbec22646111#diff-feb659bd038215868b5ac790eb5f71384485d87182d15e427ab966b9fab548afR52).

ue mod doesn't allow players to select graphics cards, if player has multi graphics cards, this bug may happen because game may render the graphics with the graphics card that os doesn't use.

**Comment by ZiYueCommentary** [comment]
This bug happends to me because im using external video card, but obviously game is using my Core Graphics card to render graphics.

**Comment by Jabka666** [comment]
Try to remove this line[]()![Screenshot_20221206-080921_GitHub.jpg](https://user-images.githubusercontent.com/41839972/205821879-6197e47c-e714-46b4-8af3-85f79760df50.jpg)

**Comment by Jabka666** [comment]
I will revert this commit then

**Comment by ZiYueCommentary** [comment]
why not make a drop-down menu to select graphics? maybe I can try it

**Comment by ZiYueCommentary** [comment]
Seems game will be blank if you set the graphics card, so i think select graphics is useless. :/
