### ISSUE TITLE
Door disappear in v1.0.3

### ISSUE THREAD

**Issue by ZiYueCommentary** [Jabka666/scpcb-ue-my#6]
![image](https://user-images.githubusercontent.com/63241389/180790671-4cdf7742-5375-4e6b-b90f-a9c103e9fcdd.png)

Door and button are disappear, but they will appear when door open.

![image](https://user-images.githubusercontent.com/63241389/180790847-2592de5c-83f4-49fd-9759-0e40e8e4e7c3.png)

Another side of this door seem okay.

![image](https://user-images.githubusercontent.com/63241389/180790992-9fb33046-8452-4c85-888b-242c7bc86981.png)

Oh and btw, I want make chinese translate version for ue mod, but v1.0.2 (latest version for now) source seems cant found in here.

**Comment by Jabka666** [comment]
Yeah, I know about this problem. I will make a separate branch called "no_opt". The doors are disappear because of unfinished optimization system. Sadly I don't have enough of knowledge, motivation and time to work on it

**Comment by Jabka666** [comment]
https://github.com/Jabka666/scpcb-ue-my/tree/no_opt
