### ISSUE TITLE
Assets aren't showed correctly on the lower floors sometimes

### ISSUE THREAD

**Issue by Jabka666** [Jabka666/scpcb-ue-my#87]

**Comment by Jabka666** [comment]
Maybe already fixed? Need checking!

**Comment by SnoeGit** [comment]
Haven't encountered issues as of yet.

**Comment by SnoeGit** [comment]
Alright, well, it appears 173's blast doors disappears when I loaded up my game after leaving the room.

**Comment by Jabka666** [comment]
We should check if the ``PlayerRoom`` is determined correctly

**Comment by Jabka666** [comment]
I think this helped to fix a bug with lower floors, but I still don't understand why it happens after loading a game sometimes
![image](https://user-images.githubusercontent.com/41839972/214100944-fd29132d-951f-43a9-bc02-02dd84f6c041.png)
