### ISSUE TITLE
Some suggets

### ISSUE THREAD

**Issue by ZiYueCommentary** [Jabka666/scpcb-ue-my#9]
You says "so many people asks why removed so many scps", so why you dont re-add those scps?

oh, what about add "Multi-Language" interface?

**Comment by Jabka666** [comment]
These SCPs are not interesting and too simple. Maybe I will add multi-language

**Comment by ZiYueCommentary** [comment]
in fact, i think main reason for many players to play ue edition many are because ue edition contains lot of scps.

...and multilanguage! its very cool, we can use windows sdk to get current windows language, and set it with game language.

**Comment by Jabka666** [comment]
Oh, you can try. That's cool!

**Comment by ZiYueCommentary** [comment]
what about crowdin? I think we can use crowdin to let more players can join into translate work.

https://crowdin.com/translate/scpcb-ue

**Comment by Jabka666** [comment]
Can you updated the file? I changed some text in my repo ``no_opt`` branch

**Comment by ZiYueCommentary** [comment]
In my concept, my website will have a [list](https://files.ziyuesinicization.site/cbue/list.txt), listed languages will display in language selector.

When player download a language pack, game will download zip file from my website, and unzip it into `Localization` folder.

Translators still need give us the language pack, so textures, subtitles and scp-294 drinks can be localized.

About `local.ini`, they will replaced by crowdin translates.

**Comment by Jabka666** [comment]
Sure!
