### ISSUE TITLE
Eletrical Center's lever didn't work in custom map

### ISSUE THREAD

**Issue by ZiYueCommentary** [Jabka666/scpcb-ue-my#93]
![](https://cdn.discordapp.com/attachments/571959646185848833/1065410802464600164/image.png)

Report by Portal Gael#9812

**Comment by Jabka666** [comment]
Did you check if event is existing?

**Comment by ZiYueCommentary** [comment]
> Did you check if event is existing?

exist

**Comment by ZiYueCommentary** [comment]
I know why this happened, but I can hardly fix this:

Now we're in `room2c_ec`, the event is `room2c_ec`, which means the lever **should** can work properly.

![image](https://user-images.githubusercontent.com/63241389/213835935-6db50917-3ecc-4d7b-bb47-caa37e02579d.png)

When we cross the 7th stair step, room becomes `room2c_ez`, instead of `room2c_ec`.

![image](https://user-images.githubusercontent.com/63241389/213836567-f436041d-7569-45ea-8d2c-20e0ad818721.png)

... and `room2c_ez` is beside the `room2c_ec`.

![image](https://user-images.githubusercontent.com/63241389/213836962-ea3b2dbd-b5dd-4594-b025-13e81b8ebbea.png)

So when we reach the 2nd floor of the electrical center, the room will still is `room2c_ec`, and `room2c_ec` does not have any event.

Map generated from map seed won't meet this bug, because `room2c_ec` will always place on the edge of the map.

![image](https://user-images.githubusercontent.com/63241389/213837979-22b1cce4-72e1-4c92-9e57-88afbfcc72f3.png)

This is the custom map for testing, remember to change the extension to `.cbmap2`.

[SITE-2.txt](https://github.com/Jabka666/scpcb-ue-my/files/10471329/SITE-2.txt)

**Comment by Jabka666** [comment]
I think this is impossible to fix, because random generation doesn't have this issue. Try to add Y-Axis in the code determining a new ``PlayerRoom``

**Comment by Jabka666** [comment]
> break

Yes, that helps
